### ISSUE TITLE
What issue does the Admin Java SDK have?

### ISSUE THREAD

**Issue by jwngr** [x1125/firebase-admin-sdk#1]
Nice library! Awesome to see an open source version of our Admin SDKs!

You mention in the `README` that the Admin Java SDK is broken. Do you mind explaining what issue you are having? We don't have a user management API for that library yet, but the library itself should work fine. If there is an issue, I'd love to help get it fixed.

**Comment by x1125** [comment]
Thank you! :)

It's not that I actually used it, but read about on the [Manage Users](https://firebase.google.com/docs/auth/admin/manage-users) site: "Warning: The Firebase Admin Java SDK does not currently have an API for managing your Firebase Authentication users.".
Somehow I can't remember why I thought it was broken. I'll change that! :)

**Comment by jwngr** [comment]
Yeah, it just hasn't been implemented yet :) We will get around to it in due time. Thanks again for putting this library together!
